/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

public class App {
    static List data;
 
    public static void main(String[] args) {
        data = new ArrayList();
        for (int i = 0; i < 100_000; i++) {
            for (int j = 0; j < i; j++) {
                data.add(j); 
            }
        }
    }
}
